CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID TEXT,
    PRODUCT_NAME TEXT,
    SUPPLIER_ID TEXT,
    CATEGORY_ID TEXT
);

INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, SUPPLIER_ID, CATEGORY_ID) VALUES
    ('1', 'CHAIR', '1', '1'),
    ('2', 'CHANG', '1', '1'),
    ('3', 'ANISEED SYRUP', '1', '2'),
    ('4', 'CHES', '2', '2');  

SELECT COUNT(PRODUCT_ID) AS Product_Count
FROM PRODUCTS;



SELECT COUNT(PRODUCT_NAME) AS Product_Count
FROM PRODUCTS;
