CREATE TABLE supplier (
  SNO TEXT PRIMARY KEY,
  SNAME TEXT,
  STATUS INTIGER,
  CITY TEXT
);

INSERT INTO supplier (SNO, SNAME, STATUS, CITY) VALUES
  ('S1', 'SMITH',20, 'LONDON'),
  ('S2', 'JONES',10, 'PARIS'),
  ('S3', 'BLAKE',20,'RID'),
  ('S5', 'ADAM' , 30,'AHTAS');

  SELECT * FROM supplier
CREATE TABLE IF NOT EXISTS STUDENT (
  ROLL_NO TEXT PRIMARY KEY,
  NAME TEXT NOT NULL,
  ADDRESS TEXT,
  AGE INTEGER

);

INSERT INTO STUDENT (ROLL_NO, NAME, ADDRESS,  AGE) VALUES
  ('7', 'AHANAF', 'DELHI',  18);

  SELECT * FROM STUDENT;

